pipeline {
    agent {
        node {
           label 'Agent-1'   
        }
    }
    environment {
        Greeting = 'Vachindroy...'
    }

    options {
        // Timeout counter starts AFTER agent is allocated
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters{
        choice(name: 'Action', choices: ['destroy', 'apply'], description: 'Pick something')
    }
    stages {
         stage('init') {
            steps {
                sh """
                    cd 01-vpc
                    terraform init
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                     cd 01-vpc
                     terraform plan
                """
            }
        }
        stage('apply') {
            when{
                expression {
                    params.Action == 'apply'
                }
            }
            input {
                message "should we continue?"
                ok "yes we should"
            }
            steps {
                sh """
                     cd 01-vpc
                     terraform apply -auto-approve
                """
            }
        }
        stage('destroy') {
             when{
                expression {
                    params.Action == 'destroy'
                }
            }
            input {
                message "should we continue?"
                ok "yes we should"
            }
            steps {
                sh """
                     cd 01-vpc
                     terraform destroy -auto-approve
                """
            }
        }
    }
    post {
        success {
            echo 'I succeeded!'
        }
        failure {
            echo 'I failed :('
        }
        always {
            echo 'all stages executed properly!'
        }
    }
}