pipeline {
    agent {
        node {
           label 'Agent-1'   
        }
    }
    environment {
        Greeting = 'Vachindroy...'
    }

    options {
        // Timeout counter starts AFTER agent is allocated
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
    }
    stages {
         stage('init') {
            steps {
                sh """
                    cd 01-vpc
                    terraform init
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                     cd 01-vpc
                     terraform plan
                """
            }
        }
        stage('destroy') {
            steps {
                sh """
                     cd 01-vpc
                     terraform destroy -auto-approve
                """
            }
        }
    }
    post {
        success {
            echo 'I succeeded!'
        }
        failure {
            echo 'I failed :('
        }
    }
}